spring:
  profiles:
    active:
      - dev
   
---
server:
 port: 9501
 application:
   name: scloud-zuul
 profiles: dev

logging:
  level:
    cn.enjoy.mapper: debug

    
zuul:
  routes:
    products:
      path: /product/**
      serviceid: scloud-config-product-client

    users:
      path: /user/**
      serviceid: scloud-user-hystrix
  ignored-services:
    "*"
  prefix: /wecloud
    
    
#eureka:
  #client: # 客户端进行Eureka注册的配置
    #service-url:
      #defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  #instance:
    #instance-id: scloud-zuul
    #prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    #lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: scloud-zuul
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
---
server:
 port: 9502
 application:
   name: scloud-zuul
 profiles: beta

logging:
  level:
    cn.enjoy.mapper: debug

    
zuul:
  routes:
    products:
      path: /product/**
      serviceid: scloud-product

    users:
      path: /user/**
      serviceid: scloud-user-hystrix
  ignored-services:
    "*"
  prefix: /wecloud
    
    
#eureka:
  #client: # 客户端进行Eureka注册的配置
    #service-url:
      #defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  #instance:
    #instance-id: scloud-zuul
    #prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    #lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: scloud-zuul
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'